services:
  db:
    image: postgres:16
    container_name: autotest_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: autotest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d autotest"]
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: autotest_redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 20

  #worker:
    #build: .
    #command: python -m app.workers.plan_generation_worker
    #environment:
      #DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      #RABBIT_URL: amqp://app:app@rabbit:5672/
      #PLAN_QUEUE: plan_generation
      #OLLAMA_BASE_URL: http://ollama:11434
      #OLLAMA_MODEL: llama3.1:8b
    #depends_on:
      #rabbit:
        #condition: service_healthy
      #db:
        #condition: service_started

  #api:
    #build: .
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    #environment:
      #DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      #RABBIT_URL: amqp://app:app@rabbit:5672/
      #PLAN_QUEUE: plan_generation
      #OLLAMA_BASE_URL: http://ollama:11434
      #OLLAMA_MODEL: llama3.1:8b
    #ports:
      #- "8000:8000"
    #depends_on:
      #rabbit:
        #condition: service_healthy
      #db:
        #condition: service_started

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  ollama:
  redisdata:
  minio_data:
